package io.github.gustavo2358.lower.testing;

import io.github.gustavo2358.air.model.*;
import io.github.gustavo2358.air.validation.*;
import io.github.gustavo2358.lower.application.*;
import io.github.gustavo2358.lower.domain.SpInput;
import java.math.BigInteger;
import java.util.List;
import java.util.Optional;

/** Independent CP3 observations; expected never generated by the lowering implementation. */
public final class LoweringSuite {
    private static int count;
    public static final LowerInput.Options OPTIONS = new LowerInput.Options(new AdmitInput.Limits(100_000, 100),
            1_000_000, ValidationOptions.defaults());
    private LoweringSuite() { }
    private static void check(boolean value, String message) {
        if (!value) throw new AssertionError("CP3 " + message);
        count++; System.out.println("lower " + count + " - " + message);
    }
    private static LoweringResult lower(SpInput input) { return new EntryGobackLowerer().lower(input, OPTIONS); }
    public static Publication observe(SpInput input, LoweringResult result) {
        check(result.status() == LoweringResult.Status.SUCCESS, "admitted input must produce SUCCESS: " + result.status());
        Publication p = result.publication().orElseThrow();
        check(result.admission().input().orElseThrow().equals(input), "entire source evidence retained");
        check(p.airVersion().equals(SemanticVersion.AIR_2_0_0) && p.units().size() == 1, "AIR 2 one unit");
        Unit u = p.units().getFirst();
        check(u.body() == Unit.BodyAvailability.AVAILABLE && u.entries().size() == 1 && u.sequences().size() == 1, "available singular shape");
        var e = u.entries().getFirst(); var s = u.sequences().getFirst();
        check(s.instructions().isEmpty() && s.terminator() instanceof Operations.Return, "typed GOBACK must be Return, never Halt");
        check(((Operations.Return) s.terminator()).values().isEmpty(), "no return values");
        check(e.signature().parameters().known().isEmpty() && e.signature().parameters().remainder() == Interactions.NoRemainder.INSTANCE, "closed known zero parameters");
        check(e.signature().results().known().isEmpty() && e.signature().results().remainder() == Interactions.NoRemainder.INSTANCE, "closed known zero results");
        check(result.entries().size() == 1 && result.statements().size() == 1, "total typed correlation");
        var entryLink = result.entries().getFirst(); var statementLink = result.statements().getFirst();
        check(entryLink.source().equals(input.entryInventory().entries().getFirst().id()) && entryLink.target().equals(e.id()), "entry identity correlation");
        check(statementLink.source().equals(input.entryInventory().entries().getFirst().start().statement().orElseThrow()), "start correlation uses published reference");
        check(entryLink.start().equals(statementLink.label()) && e.initialLabel().equals(Optional.of(statementLink.label())) && s.label().equals(statementLink.label()), "start label join closes");
        check(statementLink.target().equals(s.terminator().header().id()) && statementLink.origin().equals(s.terminator().header().origin()), "Return ID and provenance correlation");
        check(p.coverage().inventory() == Evidence.InventoryStatus.PARTIAL && u.coverage().inventory() == Evidence.InventoryStatus.PARTIAL, "alternative entry inventory stays PARTIAL");
        var gap = p.uncertainties().stream().filter(x -> x.code().equals("cobol-lower:ALTERNATE_ENTRIES_NOT_PROJECTED")).findFirst().orElseThrow();
        check(p.coverage().uncertainties().contains(gap.id()) && u.coverage().uncertainties().contains(gap.id()), "alternate gap visible in AIR coverage");
        check(p.coverage().items().size() == 2 && u.coverage().items().size() == 2, "entry and statement coverage retained");
        var precision = s.terminator().header().precision();
        check(precision.control().status() == Evidence.PrecisionStatus.EXACT, "local control exact");
        for (var dimension : List.of(Evidence.Dimension.STORAGE, Evidence.Dimension.EFFECTS, Evidence.Dimension.VALUES, Evidence.Dimension.DEPENDENCIES)) {
            var claim = precision.claim(dimension);
            check(claim.status() == Evidence.PrecisionStatus.UNAVAILABLE && !claim.reasons().isEmpty(), "no global strengthening " + dimension);
            check(p.uncertainties().stream().anyMatch(x -> claim.reasons().contains(x.id()) && x.dimensions().contains(dimension)), "dimension reason present " + dimension);
        }
        check(u.objects().isEmpty() && p.storage().isEmpty(), "zero DATA maps no storage declarations");
        check(p.capabilities().required().isEmpty() && p.capabilities().provided().isEmpty(), "no unproved AIR profile claim");
        check(result.validation().orElseThrow().equals(AirValidator.validate(p)), "complete real checker report preserved");
        check(result.validation().orElseThrow().isStructurallyValid(), "real checker GREEN");
        return p;
    }
    public static int run() {
        SpInput input = SpFixtures.minimal();
        var result = lower(input); var p = observe(input, result);
        check(lower(SpFixtures.minimal()).publication().orElseThrow().equals(p), "independent construction deterministic");
        var alteredLimits = new LowerInput.Options(new AdmitInput.Limits(200_000, 200), 2_000_000, ValidationOptions.defaults());
        check(new EntryGobackLowerer().lower(input, alteredLimits).publication().orElseThrow().equals(p), "operational metadata excluded from identity");
        for (var key : List.of(new SpInput.UnitKey("else.cbl", List.of(5, 3), "Different"),
                new SpInput.UnitKey("a:1😀", List.of(0), "b"), new SpInput.UnitKey("a", List.of(0), ":1😀b"))) {
            var renamed = SpFixtures.minimal(key, "entry:42", "statement:81");
            check(!observe(renamed, lower(renamed)).id().equals(p.id()), "revision namespace distinguishes unit and handles");
        }
        var original = p.origins().stream().filter(x -> x instanceof Origins.Written w && w.id().localId().endsWith("/original"))
                .map(x -> (Origins.Written) x).filter(x -> x.location().orElseThrow() instanceof Origins.LineColumns lc && lc.span().start().line().intValueExact() == 4).findFirst().orElseThrow();
        var span = ((Origins.LineColumns) original.location().orElseThrow()).span();
        check(span.start().equals(new Origins.Position(BigInteger.valueOf(4), BigInteger.valueOf(11)))
                && span.end().equals(new Origins.Position(BigInteger.valueOf(4), BigInteger.valueOf(16))), "exact published GOBACK original coordinates");
        check(span.lineBase().equals(BigInteger.ONE) && span.columnBase().equals(BigInteger.ZERO)
                && span.columnUnit() == Origins.ColumnUnit.UNICODE_SCALAR && !span.endExclusive(), "explicit SP coordinate conventions");
        check(original.exact() && original.includes().isEmpty(), "golden exact without include");
        check(p.origins().stream().anyMatch(x -> x instanceof Origins.Derived d && d.id().equals(p.units().getFirst().sequences().getFirst().origin())), "auxiliary sequence origin derived");
        check(!p.units().getFirst().entries().getFirst().origin().equals(p.units().getFirst().sequences().getFirst().terminator().header().origin()), "entry and GOBACK distinct origins");
        int length = p.id().localId().length();
        var tight = new LowerInput.Options(OPTIONS.admission(), length - 1, OPTIONS.validation());
        var limited = new EntryGobackLowerer().lower(input, tight);
        check(limited.status() == LoweringResult.Status.IMPLEMENTATION_LIMIT && limited.publication().isEmpty(), "identity limit never publishes prefix");
        check(new EntryGobackLowerer().lower(input, new LowerInput.Options(OPTIONS.admission(), length, OPTIONS.validation())).publication().equals(Optional.of(p)), "exact identity bound succeeds");
        var invalid = OutputAssessment.assess(ManualAir.create(true, false), ValidationOptions.defaults());
        check(invalid.status() == LoweringResult.Status.OUTPUT_INVALID && invalid.publication().isEmpty(), "invalid AIR never success");
        check(invalid.validation().equals(AirValidator.validate(ManualAir.create(true, false))), "invalid issues preserved");
        var obligation = OutputAssessment.assess(ManualAir.withProfileObligation(), ValidationOptions.defaults());
        check(obligation.validation().issues().stream().anyMatch(x -> x.kind() == ValidationIssue.Kind.SEMANTIC_OBLIGATION), "semantic obligation preserved not proved");
        var lowValidator = new EntryGobackLowerer().lower(input, new LowerInput.Options(OPTIONS.admission(), 1_000_000, new ValidationOptions(128, 1, 100)));
        check(lowValidator.status() == LoweringResult.Status.VALIDATION_INCOMPLETE && lowValidator.publication().isEmpty(), "real validation limit never success");
        check(lowValidator.validation().orElseThrow().issues().stream().anyMatch(x -> x.kind() == ValidationIssue.Kind.VALIDATION_LIMIT), "real validation limit issue preserved");
        check(lower(null).status() == LoweringResult.Status.INVALID_INPUT && lower(null).publication().isEmpty(), "in-memory input always validated");
        revisionAndEvidence(input, p);
        return count;
    }
    private static void revisionAndEvidence(SpInput input, Publication baseline) {
        check(baseline.id().localId().startsWith("minimal-entry-goback@1/AIR2/SP1.1/canonical-v1/"), "identity includes rule and semantic versions");
        var policy = input.policy();
        var policyRevision = new SpInput(input.unit(), new SpInput.Policy(policy.policyId(), "next-policy-revision", policy.qualifyMode(),
                policy.pgmnameMode(), policy.dynamMode(), policy.dllMode()), input.dataDeclarations(), input.statements(), input.structure(), input.gaps(), input.coverage(), input.entryInventory());
        check(!observe(policyRevision, lower(policyRevision)).id().equals(baseline.id()), "same unit new policy revision changes PublicationId");
        var goback = (SpInput.GobackFact) input.statements().getFirst(); var h = goback.header();
        var ordinal = SpFixtures.header(h, h.id(), 87, h.containment(), h.coverage(), h.readiness());
        var ordinalRevision = replaceHeader(input, ordinal);
        check(!observe(ordinalRevision, lower(ordinalRevision)).id().equals(baseline.id()), "same unit new structural fact changes PublicationId");
        var r = h.readiness();
        var scope = new SpInput.Readiness(new SpInput.ReadinessClaim(r.lowering().status(), "scope:😀:changed"), r.cfg(), r.effectsDataflow());
        var scopeRevision = replaceHeader(input, SpFixtures.header(h, h.id(), h.programPoint(), h.containment(), h.coverage(), scope));
        check(!observe(scopeRevision, lower(scopeRevision)).id().equals(baseline.id()), "readiness scope is revision evidence not dropped");
        var provenance = h.provenance();
        for (var location : List.of(new SpInput.Location("physical:😀/copy", 0, 0, 0, 0),
                new SpInput.Location("physical:😀/copy", 9, 3, 4, 1))) {
            var frames = List.of(new SpInput.IncludeFrame("including", "COPY:😀", "physical:😀/copy", 7),
                    new SpInput.IncludeFrame("physical:😀/copy", "NESTED", "nested", 8));
            var changed = new SpInput.Provenance(provenance.expanded(), location, frames, false);
            var revised = replaceHeader(input, new SpInput.StatementHeader(h.id(), h.programPoint(), h.containment(), changed, h.coverage(), h.readiness()));
            var lowered = lower(revised); var target = observe(revised, lowered);
            check(!target.id().equals(baseline.id()), "source provenance participates in revision");
            var originId = lowered.statements().getFirst().origin();
            var d = (Origins.Derived) target.origins().stream().filter(x -> x.id().equals(originId)).findFirst().orElseThrow();
            check(d.inputs().size() == 2 && d.rule().equals("sp-provenance/original-expanded@1"), "original and expanded roles both preserved");
            var written = (Origins.Written) target.origins().stream().filter(x -> x.id().equals(d.inputs().getFirst())).findFirst().orElseThrow();
            check(written.location().isEmpty() && !written.exact(), "unrepresentable coordinates do not fabricate span or exactness");
            check(written.includes().size() == 2 && written.includes().getFirst().requestedName().equals("COPY:😀")
                    && written.includes().stream().allMatch(x -> x.site().isEmpty()), "include chain order retained without invented site columns");
            check(target.artifacts().stream().anyMatch(x -> x.id().equals(written.artifact()) && x.logicalName().equals(location.file()) && x.contentDigest().isEmpty()), "logical source artifact not transport or fabricated digest");
            check(lowered.limitations().stream().anyMatch(x -> x.code() == LoweringResult.LimitCode.COORDINATES_UNAVAILABLE)
                    && lowered.limitations().stream().filter(x -> x.code() == LoweringResult.LimitCode.INCLUDE_SITE_UNAVAILABLE).count() == 2, "provenance limitations explicitly reported");
            check(lowered.admission().input().orElseThrow().statements().getFirst().header().provenance().equals(changed), "raw include lines and coordinates retained");
        }
        var pairA = SpFixtures.minimal(new SpInput.UnitKey("a:1😀", List.of(0), "b"), "entry:0", "statement:0");
        var pairB = SpFixtures.minimal(new SpInput.UnitKey("a", List.of(0), ":1😀b"), "entry:0", "statement:0");
        check(!lower(pairA).publication().orElseThrow().id().equals(lower(pairB).publication().orElseThrow().id()), "length framed identity resists delimiter collision");
        var e = input.entryInventory().entries().getFirst();
        var dangling = SpFixtures.entry(input, SpFixtures.entryFacts(e, new SpInput.ExecutableStart(SpInput.Availability.KNOWN,
                Optional.of(new SpInput.StatementId(input.unit(), "statement:99"))), e.signature(), e.coverage(), e.readiness(), e.gaps()));
        var failure = lower(dangling);
        check(failure.status() == LoweringResult.Status.INVALID_INPUT && failure.publication().isEmpty() && failure.validation().isEmpty(), "dangling start rejected before AIR");
        check(failure.admission().equals(new EntryGobackAdmission().admit(dangling, OPTIONS.admission())), "same semantic admission and diagnostics in lower port");
        var second = new SpInput.GobackFact(SpFixtures.header(h, new SpInput.StatementId(input.unit(), "statement:99"), 1,
                h.containment(), h.coverage(), h.readiness()), goback.exit(), goback.localContinuation());
        var c = input.coverage();
        var bigger = SpFixtures.body(input, List.of(goback, second), new SpInput.Structure(List.of(h.id(), second.header().id()), List.of()), List.of(),
                new SpInput.Coverage(c.inventoryStatus(), 2, 2, 0, 0, 0, c.readiness()));
        var unsupported = lower(bigger);
        check(unsupported.status() == LoweringResult.Status.UNSUPPORTED_SLICE && unsupported.publication().isEmpty()
                && unsupported.admission().input().orElseThrow().statements().size() == 2, "larger input never lowered as selected prefix");
        try { resultImmutable(lower(input)); } catch (UnsupportedOperationException expected) { check(true, "correlation immutable"); }
    }
    private static void resultImmutable(LoweringResult result) {
        result.statements().clear(); throw new AssertionError("mutable correlation");
    }
    private static SpInput replaceHeader(SpInput input, SpInput.StatementHeader header) {
        var g = (SpInput.GobackFact) input.statements().getFirst();
        return SpFixtures.body(input, List.of(new SpInput.GobackFact(header, g.exit(), g.localContinuation())), input.structure(), input.gaps(), input.coverage());
    }
}
