package io.github.gustavo2358.lower.testing;

import io.github.gustavo2358.air.model.*;
import io.github.gustavo2358.air.model.Ids.*;
import io.github.gustavo2358.air.validation.*;
import io.github.gustavo2358.lower.application.*;
import io.github.gustavo2358.lower.domain.SpInput;
import java.util.*;
import static io.github.gustavo2358.lower.domain.SpInput.*;

/** Relational oracle authored from the SP/AIR contracts, never generated by translation. */
public final class ScalarSuite {
    public static final LowerInput.Options OPTIONS = new LowerInput.Options(new AdmitInput.Limits(100), 32, ValidationOptions.defaults());
    private static int checks;
    private ScalarSuite() { }
    public static void check(boolean condition, String message) { if (!condition) throw new AssertionError("SCALAR " + message); checks++; }
    public static LoweringResult lower(SpInput input) { return new CobolLowerer().lower(input, OPTIONS); }
    public static LoweringResult success(SpInput input) {
        var r = lower(input); check(r.status() == LoweringResult.Status.SUCCESS, "precise input must lower: " + r.status() + " " + r.admission().diagnostics()); return r;
    }
    public static void rejected(SpInput input, String why) {
        var r = lower(input); check(r.status() != LoweringResult.Status.SUCCESS && r.publication().isEmpty(), "reject " + why);
    }
    public static void oracle(SpInput input, LoweringResult result, List<String> values, List<SpInput.DataId> targets) {
        var p = result.publication().orElseThrow();
        check(p.units().size() == 1, "one unit"); var u = p.units().getFirst();
        check(u.objects().size() == input.dataDeclarations().size(), "one Object per declaration");
        check(p.storage().size() == u.objects().size(), "one Cell per declaration");
        check(u.entries().size() == 1 && u.sequences().size() == 1, "one Sequence for linear chain");
        var sequence = u.sequences().getFirst();
        check(u.entries().getFirst().initialLabel().orElseThrow().equals(sequence.label()), "entry starts at composed Sequence");
        check(sequence.instructions().size() == values.size(), "one Assign per MOVE");
        check(sequence.terminator() instanceof Operations.Return ret && ret.values().isEmpty(), "GOBACK Return never Halt");
        check(result.data().size() == u.objects().size(), "DATA correlation complete");
        check(result.statements().size() == values.size() + 1 && result.statements().stream().allMatch(s -> s.label().equals(sequence.label())), "many statements share Label");
        check(result.operands().size() == 2 * values.size(), "operand correlation complete");
        var dataLinks = new HashMap<SpInput.DataId, LoweringResult.DataLink>(); result.data().forEach(l -> dataLinks.put(l.source(), l));
        var objects = new HashMap<ObjectId, Memory.ObjectDeclaration>(); u.objects().forEach(o -> objects.put(o.id(), o));
        var storage = new HashMap<StorageId, Memory.Cell>(); p.storage().forEach(s -> storage.put(s.header().id(), (Memory.Cell) s));
        var origins = new HashMap<OriginId, Origins.Origin>(); p.origins().forEach(o -> origins.put(o.id(), o));
        for (var d : input.dataDeclarations()) {
            var link = dataLinks.get(d.id()); check(link != null, "DATA identity mapped"); var o = objects.get(link.object()); var cell = storage.get(link.storage());
            check(o != null && cell != null && o.storage().equals(new Memory.CellBinding(cell.header().id())), "DataId Object Cell join");
            check(o.typeRef().equals(Types.known(Types.Builtin.TEXT)) && cell.typeRef().equals(o.typeRef()), "Object Cell known(text)");
            check(cell.header().owner().equals(Optional.of(u.id())) && cell.header().lifetime() == Memory.Lifetime.PERSISTENT
                && cell.header().visibility() == Memory.Visibility.PRIVATE && o.visibility() == Memory.Visibility.PRIVATE, "persistent private local storage");
            check(o.displayName().equals(Optional.of(d.canonicalName())), "name display only");
            check(origins.get(o.origin()) instanceof Origins.Derived && origins.get(cell.header().origin()) instanceof Origins.Derived, "DATA derived origins no invented spans");
        }
        var sources = new HashMap<SpInput.StatementId, MoveFact>();
        for (var s : input.statements()) if (s instanceof MoveFact m) sources.put(m.header().id(), m);
        var links = new HashMap<OperationId, LoweringResult.StatementLink>(); result.statements().forEach(l -> links.put(l.target(), l));
        var operandLinks = new HashMap<Ids.OperandId, LoweringResult.OperandLink>(); result.operands().forEach(l -> operandLinks.put(l.target(), l));
        for (int i = 0; i < values.size(); i++) {
            check(sequence.instructions().get(i) instanceof Operations.Assign, "typed Assign");
            var assign = (Operations.Assign) sequence.instructions().get(i);
            check(assign.destination() instanceof Places.ObjectPlace destination && destination.object().equals(dataLinks.get(targets.get(i)).object()), "destination by DataId, never name");
            check(assign.destination().header().role() == Operand.Role.VALUE_WRITE, "destination VALUE_WRITE");
            check(assign.value() instanceof Expressions.Literal literal && literal.value().equals(new Values.TextValue(values.get(i))), "literal exact logical text, never UNKNOWN");
            check(assign.value().header().role() == Operand.Role.VALUE_READ, "source VALUE_READ");
            check(assign.destination().header().id().owner().equals(new OperationOwner(assign.header().id()))
                && assign.value().header().id().owner().equals(new OperationOwner(assign.header().id())), "operands owned by Assign");
            var m = sources.get(links.get(assign.header().id()).source());
            check(operandLinks.get(assign.value().header().id()).source().equals(m.source().id()), "source operand correlation");
            check(operandLinks.get(assign.destination().header().id()).source().equals(m.target().id()), "destination operand correlation");
            check(hasLocation(origins, assign.value().header().origin(), m.source().provenance().original()), "literal provenance preserved");
            check(hasLocation(origins, assign.destination().header().origin(), m.target().provenance().original()), "target provenance preserved");
        }
        check(p.coverage().inventory() == Evidence.InventoryStatus.PARTIAL && u.coverage().inventory() == Evidence.InventoryStatus.PARTIAL, "partial inventory remains honest");
        check(p.uncertainties().stream().anyMatch(g -> g.code().contains("ALTERNATE_ENTRIES_NOT_PROJECTED")), "alternate entry gap retained");
        check(AirValidator.validate(p).issues().isEmpty(), "shared validator zero issues");
        check(p.id().localId().matches("[0-9a-f]{32}"), "compact PublicationId");
        for (var o : u.objects()) check(o.id().localId().matches("[0-9a-f]{32}"), "compact ObjectId");
        for (var c : p.storage()) check(c.header().id().localId().matches("[0-9a-f]{32}"), "compact StorageId");
        for (var s : sequence.instructions()) {
            check(s.header().id().localId().matches("[0-9a-f]{32}"), "compact AssignId");
            var a = (Operations.Assign)s;
            check(a.value().header().id().localId().matches("[0-9a-f]{32}") && a.destination().header().id().localId().matches("[0-9a-f]{32}"), "compact operand IDs");
        }
    }
    private static boolean hasLocation(Map<OriginId, Origins.Origin> origins, OriginId id, SpInput.Location location) {
        var todo = new ArrayDeque<OriginId>(); todo.add(id);
        while (!todo.isEmpty()) {
            var origin = origins.get(todo.removeFirst());
            if (origin instanceof Origins.Derived derived) todo.addAll(derived.inputs());
            if (origin instanceof Origins.Written w && w.location().orElse(null) instanceof Origins.LineColumns lc) {
                var span = lc.span();
                if (span.start().line().intValueExact() == location.startLine() && span.start().column().intValueExact() == location.startColumn()
                    && span.end().line().intValueExact() == location.endLine() && span.end().column().intValueExact() == location.endColumn()) return true;
            }
        }
        return false;
    }
    private static void negatives() {
        var base = ScalarInputs.create(2, 1); var m = (MoveFact)base.statements().getFirst(); var d = base.dataDeclarations().getFirst();
        var data = new ArrayList<>(base.dataDeclarations());
        data.set(0, new DataFact(d.id(), d.canonicalName(), d.picture(), d.provenance(), d.coverage(), d.readiness(), Optional.empty()));
        rejected(ScalarInputs.replace(base, data, base.statements()), "scalarText absent");
        var source = new LiteralSource(m.source().id(), ((io.github.gustavo2358.lower.domain.SpInput.LiteralSource) m.source()).kind(), Optional.empty(), m.source().provenance());
        rejected(ScalarInputs.move(base, ScalarInputs.move(m, source, m.target(), m.copySemantics(), m.normalContinuation())), "logicalValue absent");
        source = new LiteralSource(m.source().id(), LiteralKind.NUMERIC, ((io.github.gustavo2358.lower.domain.SpInput.LiteralSource) m.source()).logicalValue(), m.source().provenance());
        rejected(ScalarInputs.move(base, ScalarInputs.move(m, source, m.target(), m.copySemantics(), m.normalContinuation())), "non textual source kind");
        rejected(ScalarInputs.move(base, ScalarInputs.move(m, m.source(), ScalarInputs.target(m, m.target().binding(), Optional.empty()), m.copySemantics(), m.normalContinuation())), "wholeItemAccess absent");
        var binding = m.target().binding();
        for (var status : List.of(ResolutionStatus.AMBIGUOUS, ResolutionStatus.UNRESOLVED, ResolutionStatus.INPUT_MISSING)) {
            var b = new Binding(status, binding.candidates(), binding.selected());
            rejected(ScalarInputs.move(base, ScalarInputs.move(m, m.source(), ScalarInputs.target(m, b, m.target().wholeItemAccess()), m.copySemantics(), m.normalContinuation())), "binding not RESOLVED");
        }
        var absent = new Binding(ResolutionStatus.RESOLVED, binding.candidates(), Optional.empty());
        rejected(ScalarInputs.move(base, ScalarInputs.move(m, m.source(), ScalarInputs.target(m, absent, m.target().wholeItemAccess()), m.copySemantics(), m.normalContinuation())), "selected absent");
        var mismatch = new Binding(ResolutionStatus.RESOLVED, List.of(base.dataDeclarations().get(1).id()), Optional.of(base.dataDeclarations().get(1).id()));
        rejected(ScalarInputs.move(base, ScalarInputs.move(m, m.source(), ScalarInputs.target(m, mismatch, m.target().wholeItemAccess()), m.copySemantics(), m.normalContinuation())), "selected wholeItem mismatch");
        rejected(ScalarInputs.move(base, ScalarInputs.move(m, m.source(), m.target(), CopySemantics.UNAVAILABLE, m.normalContinuation())), "FULL_IDENTITY absent");
        for (var next : List.of(new NormalContinuation(ContinuationAvailability.UNAVAILABLE, Optional.empty(), m.normalContinuation().provenance()),
                new NormalContinuation(ContinuationAvailability.KNOWN, Optional.of(new SpInput.StatementId(base.unit(), "statement:999")), m.normalContinuation().provenance()),
                new NormalContinuation(ContinuationAvailability.KNOWN, Optional.of(m.header().id()), m.normalContinuation().provenance()))) {
            rejected(ScalarInputs.move(base, ScalarInputs.move(m, m.source(), m.target(), m.copySemantics(), next)), "unavailable dangling cyclic continuation");
        }
        rejected(ScalarInputs.replace(base, base.dataDeclarations(), List.of(m)), "GOBACK absent");
        var terminal = base.statements().getLast().header();
        rejected(ScalarInputs.replace(base, base.dataDeclarations(), List.of(m, new OtherStatement(terminal, Variant.CALL))), "terminal not GOBACK");
        var extra = new StatementHeader(new SpInput.StatementId(base.unit(), "statement:2"), 2, terminal.containment(), terminal.provenance(), terminal.coverage(), terminal.readiness());
        rejected(ScalarInputs.replace(base, base.dataDeclarations(), List.of(m, base.statements().getLast(), new OtherStatement(extra, Variant.CALL))), "unsupported extra occurrence");
        rejected(ScalarInputs.replace(base, base.dataDeclarations(), List.of(m, base.statements().getLast(), new GobackFact(extra, GobackExit.CURRENT_PROGRAM_INVOCATION, LocalContinuation.NONE))), "unreachable extra GOBACK");
        rejected(ScalarInputs.replace(base, List.of(base.dataDeclarations().get(1)), base.statements()), "referenced DATA absent");
        var tooShort = new LogicalValue(LogicalDomain.TEXT, "PROGA", 4);
        source = new LiteralSource(m.source().id(), ((io.github.gustavo2358.lower.domain.SpInput.LiteralSource) m.source()).kind(), Optional.of(tooShort), m.source().provenance());
        rejected(ScalarInputs.move(base, ScalarInputs.move(m, source, m.target(), m.copySemantics(), m.normalContinuation())), "typed extent mismatch");
        var duplicate = new ArrayList<>(base.dataDeclarations()); duplicate.add(d);
        rejected(ScalarInputs.replace(base, duplicate, base.statements()), "duplicate DATA");
    }
    private static void metamorphic() {
        var base = ScalarInputs.create(2, 2); var first = (MoveFact)base.statements().get(0); var second = (MoveFact)base.statements().get(1);
        var reversed = new ArrayList<StatementFact>(base.statements()); Collections.reverse(reversed);
        var data = new ArrayList<>(base.dataDeclarations()); Collections.reverse(data);
        var permuted = ScalarInputs.replace(base, data, reversed);
        var original = success(base); var changed = success(permuted);
        oracle(permuted, changed, List.of("PROGA", "BBBBB"), List.of(first.target().binding().selected().orElseThrow(), second.target().binding().selected().orElseThrow()));
        check(changed.publication().equals(original.publication()), "array order never controls execution or identity");
        var h = first.header(); var structural = new StatementHeader(h.id(), 991, h.containment(), h.provenance(), h.coverage(), h.readiness());
        changed = success(ScalarInputs.move(base, new MoveFact(structural, first.source(), first.target(), first.copySemantics(), first.normalContinuation())));
        check(changed.publication().equals(original.publication()), "programPoint never successor");
        var d = base.dataDeclarations().getFirst();
        data = new ArrayList<>(base.dataDeclarations()); data.set(0, new DataFact(d.id(), d.canonicalName(), Optional.of("garbage PIC ignored"), d.provenance(), d.coverage(), d.readiness(), d.scalarText()));
        check(success(ScalarInputs.replace(base, data, base.statements())).publication().equals(original.publication()), "PIC excluded from scalar semantics and revision");
        var source = new LiteralSource(first.source().id(), ((io.github.gustavo2358.lower.domain.SpInput.LiteralSource) first.source()).kind(), Optional.of(new LogicalValue(LogicalDomain.TEXT, "CCCCC", 5)), first.source().provenance());
        changed = success(ScalarInputs.move(base, ScalarInputs.move(first, source, first.target(), first.copySemantics(), first.normalContinuation())));
        check(!changed.publication().orElseThrow().id().equals(original.publication().orElseThrow().id()), "new logical value in PublicationId");
        oracle(base, original, List.of("PROGA", "BBBBB"), List.of(base.dataDeclarations().get(0).id(), base.dataDeclarations().get(1).id()));
        var sparse = ScalarInputs.create(2, 1);
        oracle(sparse, success(sparse), List.of("PROGA"), List.of(sparse.dataDeclarations().getFirst().id()));
        var shared = ScalarInputs.create(1, 8); var sr = success(shared);
        check(sr.publication().orElseThrow().units().getFirst().objects().size() == 1 && sr.publication().orElseThrow().storage().size() == 1, "shared DATA never duplicated per MOVE");
        var gap = new Gap(first.header().id(), GapScope.CAPABILITY, "INDEPENDENT_GAP", "preserved independent evidence", first.header().provenance());
        var withGap = SpFixtures.body(base, base.statements(), base.structure(), List.of(gap), base.coverage());
        check(success(withGap).publication().orElseThrow().uncertainties().stream().anyMatch(g -> g.code().equals("cobol-sp:INDEPENDENT_GAP") && g.reason().contains(gap.detail())), "independent gap preserved");
        check(new CobolLowerer().lower(SpFixtures.minimal(), OPTIONS).equals(new EntryGobackLowerer().lower(SpFixtures.minimal(), OPTIONS)), "CP3 dispatch exact model and correlations");
    }
    public static void main(String[] args) {
        int count = run() + io.github.gustavo2358.lower.application.ScalarIdentitySuite.run() + scale();
        System.out.println("LOWER_SCALAR_TESTS=" + count);
    }
    public static int run() {
        checks = 0; var input = ScalarInputs.create(1, 1); var r = success(input);
        oracle(input, r, List.of("PROGA"), List.of(input.dataDeclarations().getFirst().id()));
        negatives(); metamorphic();
        var low = new CobolLowerer().lower(input, new LowerInput.Options(new AdmitInput.Limits(1), 32, ValidationOptions.defaults()));
        check(low.status() == LoweringResult.Status.SUCCESS, "valid scalar facts need no diagnostic budget");
        return checks;
    }
    public static int scale() {
        int before = checks;
        long nVisits = 0, nRefs = 0;
        for (int size : List.of(1_000, 2_000, 10_000)) {
            int dataCount = size == 10_000 ? 1 : size;
            var input = ScalarInputs.create(dataCount, size); long start = System.nanoTime(); var result = success(input);
            long nanos = System.nanoTime() - start; var p = result.publication().orElseThrow();
            check(p.units().getFirst().objects().size() == dataCount && p.storage().size() == dataCount, "scale Objects Cells equal DATA");
            check(p.units().getFirst().sequences().getFirst().instructions().size() == size, "scale Assigns equal MOVEs");
            var stats = result.admission().statistics();
            // Six fixed indexed references per MOVE, root/entry closure and one terminal visit.
            check(stats.referencesChecked() == 7L * size + 3, "scalar reference ledger 7N+3 no scans");
            if (size == 1_000) { nVisits = stats.entitiesVisited(); nRefs = stats.referencesChecked(); }
            if (size == 2_000) check(stats.entitiesVisited() <= 2 * nVisits && stats.referencesChecked() <= 2 * nRefs, "scalar N/2N linear ledger");
            System.out.println("SCALAR_SCALE data=" + dataCount + " moves=" + size + " objects=" + p.units().getFirst().objects().size()
                + " cells=" + p.storage().size() + " assigns=" + size + " visits=" + stats.entitiesVisited()
                + " references=" + stats.referencesChecked() + " elapsed_nanos=" + nanos);
        }
        return checks - before;
    }
}
