package io.github.gustavo2358.lower.adapters.testing;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.*;
import io.github.gustavo2358.air.json.AirJson;
import io.github.gustavo2358.air.model.*;
import io.github.gustavo2358.air.model.Ids.*;
import io.github.gustavo2358.lower.adapters.cli.CobolLower;
import io.github.gustavo2358.lower.adapters.sp.SpJsonDecoder;
import io.github.gustavo2358.lower.application.*;
import java.math.BigInteger;
import java.util.*;
import java.util.function.Consumer;

/** Source fixture plus an independent small value oracle; no expected AIR generated by the lower. */
public final class ConditionNameSuite {
    private static final ObjectMapper JSON = new ObjectMapper();
    private static final SpJsonDecoder DECODER = new SpJsonDecoder(CobolLower.INPUT_LIMITS);
    public static void main(String[] args) throws Exception {
        var tree = (ObjectNode) JSON.readTree(ConditionNameSuite.class.getResourceAsStream("/sp/condition-names/checkpoint.json"));
        var result = lower(tree);
        var publication = result.publication().orElseThrow();
        if (!result.validation().orElseThrow().isStructurallyValid()) throw new AssertionError(result.validation());
        var codec = new AirJson(); var wire = codec.encode(publication);
        equal(publication, codec.decode(wire));
        var oracle = new ValuesOracle(publication);
        execute("statement:10", result, oracle);
        equal("PROGB   ", oracle.named("WS-TARGET")); // First value of each 88; last receiving operand wins.
        execute("statement:11", result, oracle);
        equal("Y", oracle.named("FLAG"));
        equal("Y", oracle.named("FLAG-RECORD")); // Child and parent view must agree after SET.
        var predicates = predicates(result);
        equal(true, oracle.value(predicates.get("statement:8").getFirst()));
        equal(List.of(true, false), predicates.get("statement:12").stream().map(oracle::value).toList());
        equal(true, oracle.value(predicates.get("statement:13").getFirst()));
        var range = predicates.get("statement:9").getFirst();
        for (long value : new long[]{7, 20, 999999999, 19, 1000000000}) {
            oracle.integerInput = BigInteger.valueOf(value);
            equal(value == 7 || value >= 20 && value <= 999999999, oracle.value(range));
        }
        if (nodes(range) > 16) throw new AssertionError("interval enumerated instead of compared");
        execute("statement:14", result, oracle);
        equal("NONE    ", oracle.named("WS-TARGET"));
        reject(tree, t -> t.remove("conditionNames"));
        reject(tree, t -> ((ArrayNode)t.path("conditionNames").path("assignments")).remove(0));
        reject(tree, t -> ((ObjectNode)t.path("conditionNames").path("assignments").get(0).path("value")).put("value", "ALT"));
        reject(tree, t -> ((ObjectNode)t.path("conditionNames").path("assignments").get(1)).put("ordinal", 0));
        reject(tree, t -> ((ObjectNode)t.path("conditionNames").path("definitions").get(1)).putNull("falseValue"));
        reject(tree, t -> ((ObjectNode)t.path("conditionNames").path("uses").get(0)).put("operand", "operand:11:0"));
        reject(tree, t -> ((ObjectNode)t.path("conditionNames").path("definitions").get(0)).put("parent", "data:999999"));
        reject(tree, t -> ((ObjectNode)t.path("conditionNames").path("uses").get(0)).put("access", "READ"));
        reject(tree, t -> t.put("contractVersion", "2.63.0"));
        reject(tree, t -> ((ObjectNode)t.path("conditionNames").path("predicates").get(0)).put("role", "INVENTED"));
        reject(tree, t -> ((ObjectNode)t.path("conditionNames").path("predicates").get(0)).put("role", "EVALUATE_WHEN/0"));
        reject(tree, t -> ((ObjectNode)t.path("conditionNames").path("definitions").get(0)).set("variableProvenance",
                t.path("conditionNames").path("definitions").get(1).path("provenance")));
        var unlocated = lower((ObjectNode)JSON.readTree(ConditionNameSuite.class.getResourceAsStream("/sp/condition-names/unlocated.json")));
        if (!unlocated.validation().orElseThrow().isStructurallyValid()) throw new AssertionError(unlocated.validation());
        codec.decode(codec.encode(unlocated.publication().orElseThrow()));
        var writes = unlocated.publication().orElseThrow().units().stream().flatMap(u -> u.sequences().stream())
                .flatMap(s -> s.instructions().stream()).toList();
        if (writes.stream().noneMatch(Operations.HavocMay.class::isInstance)) throw new AssertionError("unlocated SET must retain its write bound");
        if (writes.stream().anyMatch(Operations.Assign.class::isInstance)) throw new AssertionError("LINKAGE acquired an invented exact write");
        System.out.println("CONDITION_NAMES=PASS: ordered SET, alias, FALSE, IF, WHEN NOT, UNTIL, range, codec, adversarial closure");
    }
    private static LoweringResult lower(ObjectNode tree) throws Exception {
        var decoded = DECODER.decode(JSON.writeValueAsBytes(tree));
        if (!(decoded instanceof SpJsonDecoder.Decoded d)) throw new AssertionError(decoded);
        var result = new CobolLowerer().lower(d.input(), CobolLower.POSITIVE_OPTIONS);
        if (result.publication().isEmpty()) throw new AssertionError(result.status() + " " + result.admission().diagnostics());
        return result;
    }
    private static void reject(ObjectNode fixture, Consumer<ObjectNode> mutation) throws Exception {
        var bad = fixture.deepCopy(); mutation.accept(bad);
        var decoded = DECODER.decode(JSON.writeValueAsBytes(bad));
        if (decoded instanceof SpJsonDecoder.Decoded d && new CobolLowerer().lower(d.input(), CobolLower.POSITIVE_OPTIONS).publication().isPresent())
            throw new AssertionError("forged condition evidence admitted");
    }
    private static void equal(Object expected, Object actual) {
        if (!Objects.equals(expected, actual)) throw new AssertionError("expected " + expected + "; received " + actual);
    }
    private static Map<String,List<Expression>> predicates(LoweringResult result) {
        var owners = new HashMap<OperationId,String>();
        result.statements().forEach(l -> owners.put(l.target(), l.source().handle()));
        var byOwner = new HashMap<String,List<Sequence>>();
        for (var unit : result.publication().orElseThrow().units()) for (var sequence : unit.sequences())
            if (sequence.terminator() instanceof Operations.Branch b && owners.containsKey(b.header().id()))
                byOwner.computeIfAbsent(owners.get(b.header().id()), k -> new ArrayList<>()).add(sequence);
        var predicates = new HashMap<String,List<Expression>>();
        byOwner.forEach((owner, sequences) -> {
            var nextLabels = new HashSet<LabelId>(); var byLabel = new HashMap<LabelId,Sequence>();
            sequences.forEach(s -> { nextLabels.add(((Operations.Branch)s.terminator()).falseDestination()); byLabel.put(s.label(),s); });
            var sequence = sequences.stream().filter(s -> !nextLabels.contains(s.label())).findFirst().orElseThrow();
            var ordered = new ArrayList<Expression>();
            while (sequence != null) {
                var branch = (Operations.Branch)sequence.terminator(); ordered.add(branch.predicate());
                sequence = byLabel.get(branch.falseDestination());
            }
            equal(sequences.size(), ordered.size()); predicates.put(owner,ordered);
        });
        return predicates;
    }
    private static void execute(String source, LoweringResult result, ValuesOracle oracle) {
        var labels = new HashSet<LabelId>();
        result.statements().stream().filter(l -> l.source().handle().equals(source)).forEach(l -> labels.add(l.label()));
        int writes = 0;
        for (var unit : result.publication().orElseThrow().units()) for (var s : unit.sequences()) if (labels.contains(s.label()))
            for (var instruction : s.instructions()) {
                if (!(instruction instanceof Operations.Assign a) || !(a.destination() instanceof Places.ObjectPlace p))
                    throw new AssertionError("proved text SET must have an exact assignment");
                oracle.memory.put(oracle.location(p.object()), oracle.value(a.value())); writes++;
            }
        if (writes == 0) throw new AssertionError("SET has no executable writes");
    }
    private static int nodes(Expression root) {
        int count = 0; var todo = new ArrayDeque<Expression>(); todo.push(root);
        while (!todo.isEmpty()) {
            var e = todo.pop(); count++;
            if (e instanceof Expressions.Binary b) { todo.push(b.left()); todo.push(b.right()); }
            else if (e instanceof Expressions.Unary u) todo.push(u.argument());
            else if (e instanceof Expressions.Unknown u) todo.addAll(u.dependencies());
        }
        return count;
    }
    /** Scalar evaluator only for this bounded, hand-written test oracle. */
    private static final class ValuesOracle {
        final Map<ObjectId,Memory.ObjectDeclaration> objects = new HashMap<>();
        final Map<Object,Object> memory = new HashMap<>();
        BigInteger integerInput;
        ValuesOracle(Publication publication) {
            publication.units().forEach(u -> u.objects().forEach(o -> objects.put(o.id(),o)));
        }
        Object location(ObjectId id) {
            var o = objects.get(id);
            return o.storage() instanceof Memory.CellBinding c ? c.storage() : id;
        }
        Object named(String name) {
            var object = objects.values().stream().filter(o -> o.displayName().filter(name::equals).isPresent()).findFirst().orElseThrow();
            return memory.get(location(object.id()));
        }
        Object value(Expression expression) {
            if (expression instanceof Expressions.Literal l) {
                if (l.value() instanceof Values.TextValue t) return t.value();
                if (l.value() instanceof Values.IntValue i) return i.value();
            }
            if (expression instanceof Expressions.Read r && r.place() instanceof Places.ObjectPlace p) {
                var value = memory.get(location(p.object()));
                if (value == null) throw new AssertionError("read before oracle setup " + objects.get(p.object()).displayName());
                return value;
            }
            if (expression instanceof Expressions.Unknown u && u.typeRef().equals(Types.known(Types.Builtin.INT)))
                return Objects.requireNonNull(integerInput); // Arbitrary value of the explicitly unlocated integer receiver.
            if (expression instanceof Expressions.FitText f) {
                var text = (String)value(f.value()); int length = f.length().intValueExact();
                return text.length() >= length ? text.substring(0,length) : text + f.pad().repeat(length-text.length());
            }
            if (expression instanceof Expressions.SliceText s) {
                var text = (String)value(s.value()); int start = ((BigInteger)value(s.start())).intValueExact();
                return text.substring(start, start + ((BigInteger)value(s.count())).intValueExact());
            }
            if (expression instanceof Expressions.Unary u && u.operator() == Expressions.UnaryOperator.NOT) return !(Boolean)value(u.argument());
            if (expression instanceof Expressions.Binary b) {
                var left = value(b.left()); var right = value(b.right());
                return switch (b.operator()) {
                    case EQ -> left.equals(right);
                    case NE -> !left.equals(right);
                    case GE -> ((BigInteger)left).compareTo((BigInteger)right) >= 0;
                    case LE -> ((BigInteger)left).compareTo((BigInteger)right) <= 0;
                    case AND -> (Boolean)left && (Boolean)right;
                    case OR -> (Boolean)left || (Boolean)right;
                    case CONCAT -> (String)left + right;
                    default -> throw new AssertionError("unexpected oracle operator");
                };
            }
            throw new AssertionError("unexpected oracle expression " + expression);
        }
    }
}
