package io.github.gustavo2358.lower.adapters.testing;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import io.github.gustavo2358.lower.adapters.sp.SpJsonDecoder;
import io.github.gustavo2358.lower.domain.SpInput;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.util.ArrayList;
import java.util.HexFormat;
import java.util.List;
import static io.github.gustavo2358.lower.domain.SpInput.*;
import static io.github.gustavo2358.lower.adapters.sp.SpJsonDecoder.*;

/** Independent observations frozen in CP1-contract.md, never expected generated by the decoder. */
public final class DecoderSuite {
    private static final ObjectMapper JSON = new ObjectMapper();
    private static final SpJsonDecoder DECODER = new SpJsonDecoder(new Limits(64));
    private static int assertions;
    private DecoderSuite() { }
    private static void check(boolean value, String message) {
        if (!value) throw new AssertionError(message);
        assertions++;
    }
    private static byte[] bytes(JsonNode node) throws Exception { return JSON.writeValueAsBytes(node); }
    private static Decoded decoded(byte[] bytes) {
        var result = DECODER.decode(bytes);
        check(result instanceof Decoded, "golden/valid physical input must decode: " + result);
        return (Decoded) result;
    }
    private static void rejects(byte[] bytes, Code code) {
        var result = DECODER.decode(bytes);
        check(result instanceof Rejected, "must reject " + code);
        var diagnostic = ((Rejected) result).diagnostic();
        check(diagnostic.code() == code, "diagnostic expected " + code + ", got " + diagnostic);
        check(!diagnostic.phase().isBlank() && !diagnostic.location().isBlank(), "physical phase/location required");
    }
    private static ObjectNode signature(ObjectNode node) {
        return (ObjectNode) node.path("entryInventory").path("entries").get(0).path("signature");
    }
    private static void physical(ObjectNode golden, byte[] raw) throws Exception {
        for (String version : List.of("1.0.0", "1.5.0", "2.0.0")) {
            var value = golden.deepCopy(); value.put("contractVersion", version);
            rejects(bytes(value), Code.UNSUPPORTED_CONTRACT);
        }
        var masquerade = golden.deepCopy(); masquerade.put("contractVersion", "1.4.0");
        rejects(bytes(masquerade), Code.INPUT_ERROR); // SP1.1 bytes cannot impersonate the new closed SP1.4 shape.
        var value = golden.deepCopy(); value.put("schema", "other");
        rejects(bytes(value), Code.UNSUPPORTED_CONTRACT);
        rejects("{".getBytes(StandardCharsets.UTF_8), Code.INPUT_ERROR);
        rejects((new String(raw, StandardCharsets.UTF_8) + " {}").getBytes(StandardCharsets.UTF_8), Code.INPUT_ERROR);
        rejects(new String(raw, StandardCharsets.UTF_8).replace("\"schema\":", "\"schema\":\"wrong\",\"schema\":").getBytes(StandardCharsets.UTF_8), Code.INPUT_ERROR);
        rejects(new String(raw, StandardCharsets.UTF_8).replace("\"parameterCount\":0", "\"parameterCount\":1,\"parameterCount\":0").getBytes(StandardCharsets.UTF_8), Code.INPUT_ERROR);
        for (String field : List.of("schema", "contractVersion", "unit", "policy", "statements", "dataDeclarations", "entryInventory", "coverage", "gaps", "structure")) {
            value = golden.deepCopy(); value.remove(field); rejects(bytes(value), Code.INPUT_ERROR);
            value = golden.deepCopy(); value.putNull(field); rejects(bytes(value), Code.INPUT_ERROR);
        }
        value = golden.deepCopy(); signature(value).remove("parameterCount"); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); signature(value).put("parameterCount", "0"); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); signature(value).put("parameterCount", 0.5); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); signature(value).put("parameterCount", 2147483648L); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); signature(value).put("availability", "FUTURE"); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); signature(value).put("returningClause", 0); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); ((ObjectNode)value.path("unit")).put("canonicalProgramName", 123); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); ((ObjectNode)value.path("unit")).put("canonicalProgramName", 1.25); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); ((ObjectNode)value.path("statements").get(0).path("header").path("provenance").path("original")).put("file", true); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); signature(value).putNull("parameterCount");
        check(decoded(bytes(value)).input().entryInventory().entries().get(0).signature().parameterCount().isEmpty(), "null count must remain absent, never zero");
        value = golden.deepCopy(); value.put("unknown", true); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); signature(value).put("unknown", true); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); ((ObjectNode)value.path("statements").get(0)).put("variant", "FUTURE"); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); ((ObjectNode)value.path("statements").get(0).path("header")).put("programPoint", "0"); rejects(bytes(value), Code.INPUT_ERROR);
        value = golden.deepCopy(); ((ObjectNode)value.path("statements").get(0).path("header").path("provenance")).put("exact", "true"); rejects(bytes(value), Code.INPUT_ERROR);
        for (Limits limit : List.of(new Limits(1))) {
            var result = new SpJsonDecoder(limit).decode(raw);
            check(result instanceof Rejected r && r.diagnostic().code() == Code.IMPLEMENTATION_LIMIT, "limit never truncates input");
        }
    }
    private static JsonNode reordered(JsonNode value) {
        if (value instanceof ObjectNode object) {
            var result = JSON.createObjectNode();
            var names = new ArrayList<String>(); object.fieldNames().forEachRemaining(names::add);
            java.util.Collections.reverse(names);
            names.forEach(n -> result.set(n, reordered(object.get(n)))); return result;
        }
        if (value instanceof ArrayNode array) {
            var result = JSON.createArrayNode(); array.forEach(v -> result.add(reordered(v))); return result;
        }
        return value.deepCopy();
    }
    private static void variants(ObjectNode golden) throws Exception {
        var base = (ObjectNode)golden.path("statements").get(0);
        var provenance = base.path("header").path("provenance");
        var reference = JSON.createObjectNode(); reference.put("id", "operand:1:0").put("role", "READ").set("provenance", provenance);
        var binding = reference.putObject("binding"); binding.put("status", "UNRESOLVED").put("reason", "DECLARATION_NOT_FOUND").putNull("selected").putArray("candidates");
        for (String kind : List.of("MOVE", "CALL", "IF", "OBSERVED")) {
            var value = golden.deepCopy(); var extra = JSON.createObjectNode(); extra.put("variant", kind);
            var header = base.path("header").deepCopy(); ((ObjectNode)header).put("id", "statement:1"); extra.set("header", header);
            switch (kind) {
                case "MOVE" -> {
                    var literal = extra.putObject("source"); literal.put("id", "operand:1:1").put("kind", "UNKNOWN").put("value", "A").set("provenance", provenance);
                    extra.set("target", reference);
                }
                case "CALL" -> { extra.put("syntax", "IDENTIFIER_OR_EXPRESSION").put("runtimeTarget", "UNKNOWN").put("runtimeUncertaintyCode", "DYNAMIC_CALL_TARGET_VALUE_UNKNOWN"); extra.set("operand", reference); }
                case "IF" -> { extra.put("explicitlyTerminated", true).putNull("continuation"); var condition = extra.putObject("condition"); condition.put("shape", "RELATION").set("provenance", provenance); condition.putArray("references").add(reference); }
                case "OBSERVED" -> extra.put("observedKind", "GOBACK").put("observedShape", "GOBACK").put("gapCode", "SYNTHETIC_UNSUPPORTED");
                default -> throw new AssertionError("test variant");
            }
            ((ArrayNode)value.path("statements")).add(extra);
            var result = decoded(bytes(value));
            check(result.input().statements().size() == 2, "known variant occurrence must survive");
            check(result.input().statements().get(1) instanceof OtherStatement other && other.variant().name().equals(kind), "known unsupported variant never becomes GOBACK");
            check(result.unsupportedVariants().equals(List.of(new UnsupportedVariant(new StatementId(result.input().unit(), "statement:1"), Variant.valueOf(kind)))), "stable variant and ID diagnostic");
            extra.put("unknown", 0); rejects(bytes(value), Code.INPUT_ERROR);
        }
    }
    private static void immutable(SpInput input, byte[] raw) throws Exception {
        var statements = new ArrayList<>(input.statements());
        var entries = new ArrayList<>(input.entryInventory().entries());
        var codes = new ArrayList<>(input.entryInventory().gapCodes());
        var path = new ArrayList<>(input.unit().structuralPath());
        var key = new UnitKey(input.unit().compilationUnitId(), path, input.unit().canonicalProgramName());
        var inventory = new EntryInventory(input.entryInventory().status(), input.entryInventory().scope(), entries, codes);
        var copy = new SpInput(key, input.policy(), input.dataDeclarations(), statements, input.structure(), input.gaps(), input.coverage(), inventory);
        statements.clear(); entries.clear(); codes.clear(); path.clear();
        check(copy.equals(input), "defensive copies retain all nested collections");
        try { copy.statements().clear(); throw new AssertionError("mutable exposed list"); } catch (UnsupportedOperationException expected) { assertions++; }
        var file = Files.createTempFile("lower-decoder-lifetime-", ".json");
        try {
            Files.write(file, raw); var retained = decoded(Files.readAllBytes(file)).input();
            Files.delete(file); check(retained.equals(input), "input survives file removal");
        } finally { Files.deleteIfExists(file); }
    }

    private static void extendedSurface(ObjectNode golden) throws Exception {
        // Synthetic physical surface, not a semantic validity claim or another capability.
        var value = golden.deepCopy();
        var header = (ObjectNode)value.path("statements").get(0).path("header");
        var provenance = (ObjectNode)header.path("provenance");
        ((ObjectNode)provenance.path("original")).put("file", "never-open-ç.cbl").put("startColumn", 23);
        ((ArrayNode)provenance.path("includeChain")).addObject().put("includingFile", "outer.cbl")
            .put("requestedName", "PUBLIC-COPY").put("includedFile", "copy.cpy").put("includeLine", 9);
        var entry = (ObjectNode)value.path("entryInventory").path("entries").get(0);
        var gap = ((ArrayNode)entry.path("gaps")).addObject();
        gap.put("scope", "ENTRY_SIGNATURE").put("code", "SYNTHETIC_GAP").put("detail", "kept").set("provenance", provenance);
        var statementGap = ((ArrayNode)value.path("gaps")).addObject();
        statementGap.put("statement", "statement:0").put("scope", "STRUCTURE").put("code", "SYNTHETIC_STRUCTURE").put("detail", "kept").set("provenance", provenance);
        var data = ((ArrayNode)value.path("dataDeclarations")).addObject();
        data.put("id", "data:4").put("canonicalName", "ITEM").putNull("picture").put("coverage", "PARTIAL")
            .set("provenance", provenance);
        data.set("readiness", header.path("readiness"));
        var branch = ((ArrayNode)value.path("structure").path("branches")).addObject();
        branch.put("parent", "statement:0").put("branch", "THEN").putArray("children").add("statement:0");
        var input = decoded(bytes(value)).input();
        check(input.statements().get(0).header().provenance().includeChain().equals(List.of(new IncludeFrame("outer.cbl", "PUBLIC-COPY", "copy.cpy", 9))), "include chain retained exactly");
        check(input.statements().get(0).header().provenance().original().file().equals("never-open-ç.cbl") && input.statements().get(0).header().provenance().original().startColumn() == 23, "source text and coordinates preserved without opening");
        check(input.dataDeclarations().size() == 1 && input.dataDeclarations().get(0).id().equals(new DataId(input.unit(), "data:4")) && input.dataDeclarations().get(0).picture().isEmpty(), "DATA occurrence and null picture retained");
        check(input.gaps().get(0).statement().equals(new StatementId(input.unit(), "statement:0")) && input.entryInventory().entries().get(0).gaps().get(0).code().equals("SYNTHETIC_GAP"), "localized gaps retained");
        check(input.structure().branches().get(0).children().equals(List.of(new StatementId(input.unit(), "statement:0"))), "branch relations retained without interpreting control");
        var renamed = bytes(golden);
        var text = new String(renamed, StandardCharsets.UTF_8).replace("statement:0", "statement:73").replace("entry:0", "entry:91");
        var mapped = decoded(text.getBytes(StandardCharsets.UTF_8)).input();
        check(mapped.entryInventory().entries().get(0).id().handle().equals("entry:91") && mapped.entryInventory().entries().get(0).start().statement().orElseThrow().handle().equals("statement:73") && mapped.structure().roots().get(0).handle().equals("statement:73"), "consistent arbitrary handles preserved");
    }
    public static void main(String[] ignored) throws Exception {
        assertions += ScalarWireSuite.run();
        assertions += CallIntegrationSuite.run();
        assertions += IfIntegrationSuite.run();
        byte[] raw;
        try (var stream = DecoderSuite.class.getResourceAsStream("/sp/cobol-semantic-product.json")) {
            if (stream == null) throw new AssertionError("golden missing"); raw = stream.readAllBytes();
        }
        check(HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(raw)).equals("7ebce874bb98262598b908b176290368f738a21561c35a6ac342fc72e66d04ed"), "real upstream golden digest");
        var result = decoded(raw); var input = result.input();
        check(result.unsupportedVariants().isEmpty(), "golden has no unsupported variant");
        check(input.unit().equals(new UnitKey("SEMANTIC-PRODUCT-ENTRY-GOBACK.CBL", List.of(0), "AIR-FIRST")), "manual namespace oracle");
        check(input.statements().size() == 1 && input.statements().get(0) instanceof GobackFact, "typed single GOBACK");
        var goback = (GobackFact)input.statements().get(0); var entry = input.entryInventory().entries().get(0);
        check(entry.id().equals(new EntryId(input.unit(), "entry:0")) && entry.role() == EntryRole.PRIMARY && entry.availability() == Availability.KNOWN, "entry oracle");
        check(entry.start().availability() == Availability.KNOWN && entry.start().statement().orElseThrow().equals(new StatementId(input.unit(), "statement:0")), "explicit start preserved");
        check(entry.signature().availability() == Availability.KNOWN && entry.signature().parameterCount().orElseThrow() == 0 && entry.signature().returningClause() == ReturningClause.ABSENT, "known zero signature");
        check(goback.exit() == GobackExit.CURRENT_PROGRAM_INVOCATION && goback.localContinuation() == LocalContinuation.NONE, "local exit exact");
        check(input.entryInventory().status() == InventoryStatus.PARTIAL && input.entryInventory().scope() == EntryInventoryScope.PRIMARY_ONLY && input.entryInventory().gapCodes().equals(List.of("ALTERNATE_ENTRIES_NOT_PROJECTED")), "alternate inventory remains partial");
        check(input.dataDeclarations().isEmpty() && input.gaps().isEmpty() && input.structure().branches().isEmpty() && input.structure().roots().equals(List.of(goback.header().id())), "complete golden inventories");
        check(input.coverage().inventoryStatus() == InventoryStatus.COMPLETE && input.coverage().observedStatements() == 1 && input.coverage().modeledStatements() == 1 && input.coverage().partialStatements() == 0 && input.coverage().unsupportedStatements() == 0 && input.coverage().inputMissingStatements() == 0, "coverage counts oracle");
        check(entry.provenance().original().equals(new Location("semantic-product-entry-goback.cbl", 3, 7, 4, 18)) && goback.header().provenance().original().equals(new Location("semantic-product-entry-goback.cbl", 4, 11, 4, 16)), "manual original coordinates oracle");
        check(entry.provenance().exact() && goback.header().provenance().exact() && entry.provenance().includeChain().isEmpty(), "provenance not invented");
        check(goback.header().readiness().lowering().status() == ReadinessStatus.SUFFICIENT && goback.header().readiness().effectsDataflow().status() == ReadinessStatus.BLOCKED, "dimensions not conflated");
        check(input.policy().qualifyMode() == QualifyMode.UNSPECIFIED && input.policy().pgmnameMode() == PgmnameMode.UNSPECIFIED && input.policy().dynamMode() == DynamMode.UNSPECIFIED && input.policy().dllMode() == DllMode.UNSPECIFIED, "no convenient option default");
        var golden = (ObjectNode) JSON.readTree(raw);
        physical(golden, raw); variants(golden); immutable(input, raw); extendedSurface(golden);
        check(decoded(bytes(reordered(golden))).input().equals(input), "property order is immaterial");
        var renamed = golden.deepCopy(); ((ObjectNode)renamed.path("unit")).put("canonicalProgramName", "OTHER");
        check(!decoded(bytes(renamed)).input().statements().get(0).header().id().equals(goback.header().id()), "same local handle in distinct namespace is distinct");
        int semantic = assertions + AdmissionAdapterSuite.run(raw) + VerticalSuite.run(raw);
        int performance = Boolean.getBoolean("lower.performance") ? DecoderPerformanceSuite.run(raw) : 0;
        System.out.println("LOWER_TESTS=" + (semantic + performance));
        if (Boolean.getBoolean("lower.performance")) System.out.println("LOWER_PERFORMANCE_TESTS=" + performance);
    }
}
