package io.github.gustavo2358.lower.adapters.testing;
import io.github.gustavo2358.lower.adapters.cli.CobolLower;
import io.github.gustavo2358.lower.adapters.sp.SpJsonDecoder;
import io.github.gustavo2358.lower.application.*;
import io.github.gustavo2358.lower.domain.FileFacts;
import io.github.gustavo2358.lower.domain.SpInput;
import io.github.gustavo2358.air.model.*;
import java.util.*;
import static io.github.gustavo2358.lower.testing.CallOracle.check;

/** Hand-written semantic oracles over producer fixtures; no expected output generated by the lower. */
public final class FileNativeOperationSuite {
    static byte[] bytes(String fixture)throws Exception{return Objects.requireNonNull(FileNativeOperationSuite.class.getResourceAsStream("/sp/file-dependencies/w2/"+fixture+".json")).readAllBytes();}
    public static void main(String[] args)throws Exception {
        var decoder=new SpJsonDecoder(CobolLower.INPUT_LIMITS);var decoded=decoder.decode(bytes("native"));
        check(decoded instanceof SpJsonDecoder.Decoded,"FD-W2 SP2.23 must decode: "+decoded);
        var input=((SpJsonDecoder.Decoded)decoded).input();
        var write=input.fileInventory().operations().uses().stream().filter(u->u.command()==FileFacts.Command.WRITE).findFirst().orElseThrow();
        check(write.surface().orElseThrow().operands().stream().map(FileFacts.Operand::role).collect(java.util.stream.Collectors.toSet()).equals(Set.of(FileFacts.OperandRole.RECORD,FileFacts.OperandRole.FROM)),"WRITE roles decoded");
        check(write.surface().orElseThrow().operands().stream().allMatch(o->!o.references().isEmpty()),"canonical operand refs decoded");
        var old=new SpJsonDecoder(CobolLower.INPUT_LIMITS).decode(Objects.requireNonNull(FileNativeOperationSuite.class.getResourceAsStream("/sp/file-dependencies/static.json")).readAllBytes());
        check(old instanceof SpJsonDecoder.Decoded d&&d.input().fileInventory().operations().uses().stream().allMatch(u->u.surface().isEmpty()),"historical SP2.22 structure unavailable");
var result=new CobolLowerer().lower(input,CobolLower.OPTIONS);
        check(result.publication().isPresent(),"FD-W2 native publication: "+result);var p=result.publication().orElseThrow();
        var invokes=p.units().getFirst().sequences().stream().map(Sequence::terminator).filter(Operations.Invoke.class::isInstance).map(Operations.Invoke.class::cast).toList();
        check(invokes.size()==7,"seven native uses");
        check(invokes.stream().map(Operations.Invoke::action).collect(java.util.stream.Collectors.toSet()).equals(Set.of("open","read","write","rewrite","delete-record","start","close")),"seven source operations, no physical deletion");
        for(var i:invokes){check(i.target() instanceof Interactions.LiteralTarget t&&t.name().equals("CLIENTDD"),"all sites own F, not FROM owner G");check(i.effectBound().otherwise().mustOverwrite().isEmpty(),"no speculative MUST");}
        var other=p.resources().stream().filter(r->r.declaration().orElseThrow().name().equals("G")).findFirst().orElseThrow();
        check(other.declaration().orElseThrow().uses().isEmpty(),"FROM OTHER-R is no G file use");
        var codec=new io.github.gustavo2358.air.json.AirJson();check(codec.decode(codec.encode(p)).equals(p),"native codec roundtrip");
        check(new CobolLowerer().lower(input,CobolLower.OPTIONS).publication().orElseThrow().equals(p),"native determinism");
        var handlers=decoder.decode(bytes("delete-handlers"));check(handlers instanceof SpJsonDecoder.Decoded,"handlers decode");
        var h=new CobolLowerer().lower(((SpJsonDecoder.Decoded)handlers).input(),CobolLower.OPTIONS).publication().orElseThrow();
        var hs=h.units().getFirst().sequences();var calls=hs.stream().map(Sequence::terminator).filter(Operations.Invoke.class::isInstance).map(Operations.Invoke.class::cast).toList();
        check(calls.size()==3,"one DELETE, two CALL, exactly once");
        var deletion=calls.stream().filter(i->i.action().equals("delete-record")).findFirst().orElseThrow();
        var callLabels=hs.stream().filter(s->s.terminator() instanceof Operations.Invoke i&&!i.action().equals("delete-record")).map(Sequence::label).collect(java.util.stream.Collectors.toSet());
        check(deletion.outcomes().known().stream().noneMatch(a->a instanceof Control.Normal n&&callLabels.contains(n.label())),"handler must not be unconditional normal successor");
        var mapper=new com.fasterxml.jackson.databind.ObjectMapper();var base=(com.fasterxml.jackson.databind.node.ObjectNode)mapper.readTree(bytes("delete-handlers"));
        for(var mutation:List.of("missing-handlers","missing-options","foreign-body","duplicate-handler","self-body","foreign-operand","bad-relation")) {
            var doc=base.deepCopy();var use=(com.fasterxml.jackson.databind.node.ObjectNode)doc.path("fileInventory").path("operations").path("uses").get(0);
            var body=(com.fasterxml.jackson.databind.node.ArrayNode)use.path("handlers").get(0).path("statements");
            switch(mutation){
                case "missing-handlers"->use.remove("handlers");case "missing-options"->use.remove("options");
                case "foreign-body"->body.set(0,mapper.valueToTree("statement:999"));case "self-body"->body.set(0,use.path("statement"));
                case "duplicate-handler"->((com.fasterxml.jackson.databind.node.ArrayNode)use.path("handlers")).add(use.path("handlers").get(0).deepCopy());
                case "foreign-operand"->{var operand=((com.fasterxml.jackson.databind.node.ObjectNode)mapper.readTree(bytes("native")).path("fileInventory").path("operations").path("uses").get(1).path("operands").get(0)).deepCopy();((com.fasterxml.jackson.databind.node.ArrayNode)operand.path("references")).set(0,mapper.valueToTree("operand:999"));((com.fasterxml.jackson.databind.node.ArrayNode)use.path("operands")).add(operand);}
                case "bad-relation"->use.put("keyRelation","GREATER");
            }
            var d=decoder.decode(mapper.writeValueAsBytes(doc));check(d instanceof SpJsonDecoder.Rejected||new CobolLowerer().lower(((SpJsonDecoder.Decoded)d).input(),CobolLower.OPTIONS).status()==LoweringResult.Status.INVALID_INPUT,"reject "+mutation);
        }
        var original=write.surface().orElseThrow();
        for(var bad:List.of(new FileFacts.Surface(original.operands(),List.of(FileFacts.Option.NEXT),original.keyRelation(),false,List.of()),
                new FileFacts.Surface(original.operands(),original.options(),FileFacts.KeyRelation.GREATER,false,List.of()),
                new FileFacts.Surface(original.operands(),original.options(),original.keyRelation(),false,List.of(new FileFacts.Handler(FileFacts.HandlerKind.INVALID_KEY,List.of(write.statement()),write.provenance()))))) {
            var changed=new FileFacts.Use(write.statement(),write.ordinal(),write.command(),write.mode(),write.profile(),write.bindingStatus(),write.candidates(),write.provenance(),write.gapCodes(),Optional.of(bad));
            check(new CobolLowerer().lower(replace(input,write,changed),CobolLower.OPTIONS).status()==LoweringResult.Status.INVALID_INPUT,"memory admission rejects invalid options/relation/body");
        }
        var wrongOwner=new FileFacts.Use(write.statement(),write.ordinal(),write.command(),write.mode(),write.profile(),write.bindingStatus(),List.of(new FileFacts.Candidate(input.fileInventory().declarations().stream().filter(f->f.logicalFile().equals("G")).findFirst().orElseThrow().id(),input.unit())),write.provenance(),write.gapCodes(),write.surface());
        check(new CobolLowerer().lower(replace(input,write,wrongOwner),CobolLower.OPTIONS).status()==LoweringResult.Status.INVALID_INPUT,"memory record owner spoof rejected");
        System.out.println("FD_W2_NATIVE=PASS seven verbs, record owner, FROM isolation, handlers, admission, codec, determinism");
    }
    private static SpInput replace(SpInput i,FileFacts.Use before,FileFacts.Use after) {
        var f=i.fileInventory();var ops=f.operations();var uses=ops.uses().stream().map(u->u.equals(before)?after:u).toList();
        return new SpInput(i.unit(),i.policy(),i.dataDeclarations(),i.statements(),i.structure(),i.gaps(),i.coverage(),i.entryInventory(),i.storageIndependence(),i.compositional(),i.storage(),new FileFacts.Inventory(f.availability(),f.declarations(),f.gapCodes(),new FileFacts.Operations(ops.availability(),uses,ops.gapCodes())));
    }
}
