"""CP5 contract oracles, authored before closure support; not generated by checks."""
import json
from pathlib import Path
import sys
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "scripts/harness"))
import checks
from lifecycle_fixture import ACTIVE, MANIFEST, activate_fixture, close_fixture, copy_checkout, revoke_active_authority


class Closure(unittest.TestCase):
    def setUp(self):
        temp = tempfile.TemporaryDirectory(prefix="lower-closure-oracle-")
        self.addCleanup(temp.cleanup)
        self.root = Path(temp.name)
        copy_checkout(self.root)
        close_fixture(self.root)

    def registry(self, change):
        path = self.root / "docs/work/registry.json"
        data = json.loads(path.read_text())
        change(data)
        path.write_text(json.dumps(data))

    def rejects(self, code="HISTORY"):
        errors = checks.document_errors(self.root)
        self.assertTrue(any(code in e for e in errors), (code, errors))

    def resolve(self):
        resolver = getattr(checks, "work_manifest", None)
        self.assertTrue(callable(resolver), "registered lifecycle resolver is missing")
        return resolver(self.root, "WORK-LOWER-001")

    def test_closed_baseline(self):
        self.assertEqual([], checks.document_errors(self.root))

    def test_closed_resolution(self):
        self.assertEqual("CP5", self.resolve()["authorization"]["current_checkpoint"])

    def test_active_resolution_and_old_baseline(self):
        activate_fixture(self.root)
        self.assertEqual([], checks.document_errors(self.root))
        self.assertEqual("active", self.resolve()["status"])

    def test_missing_registration_no_fallback(self):
        self.registry(lambda r: r.update(history=[]))
        with self.assertRaisesRegex(ValueError, "WORK_REGISTRATION"):
            self.resolve()

    def test_duplicate_registration(self):
        self.registry(lambda r: r["history"].append(dict(r["history"][0])))
        self.rejects()
        with self.assertRaisesRegex(ValueError, "WORK_REGISTRATION"):
            self.resolve()

    def test_unregistered_active_copy(self):
        (self.root / ACTIVE).mkdir(parents=True)
        self.rejects()

    def test_external_manifest(self):
        self.registry(lambda r: r["history"][0].update(manifest="/tmp/arbitrary.yaml"))
        self.rejects()

    def test_missing_evidence(self):
        self.registry(lambda r: r["history"][0].update(evidence="docs/missing.json"))
        self.rejects()

    def test_arbitrary_history_does_not_authorize_code(self):
        revoke_active_authority(self.root)
        self.assertEqual([], checks.document_errors(self.root))
        self.registry(lambda r: r.update(history=[dict(id="WORK-LOWER-999")]))
        self.rejects("UNAUTHORIZED_IMPLEMENTATION")

    def test_missing_authority(self):
        path = self.root / MANIFEST
        data = checks.read_data(path)
        data["authorization"].pop("authority")
        import yaml
        path.write_text(yaml.safe_dump(data))
        self.rejects()

    def test_final_checkpoint_not_authorized(self):
        path = self.root / MANIFEST
        data = checks.read_data(path)
        data["authorization"]["authorized_checkpoints"].remove("CP5")
        import yaml
        path.write_text(yaml.safe_dump(data))
        self.rejects()

    def test_git_mismatch(self):
        self.registry(lambda r: r["history"][0].update(pull_request=999))
        self.rejects()

    def test_dependency_receipt_missing(self):
        (self.root / "docs/quality/WORK-LOWER-001/CP4-remote.json").unlink()
        self.rejects("DEPENDENCY")

    def test_backlog_not_closed(self):
        self.registry(lambda r: r["backlog"][0].update(status="in_progress"))
        self.rejects()

    def test_index_missing(self):
        (self.root / "docs/work/index.md").write_text("# Nothing registered\n")
        self.rejects("INDEX")

    def test_failed_certificate_is_not_certifiable(self):
        record = checks.read_data(self.root / "docs/quality/WORK-LOWER-001/CP5.json")
        record["certification"]["status"] = "FAIL"
        self.assertIn("CERTIFICATE status", checks.certificate_errors(self.root, record))


if __name__ == "__main__":
    unittest.main(verbosity=2)
