package io.github.gustavo2358.lower.adapters.source;
import java.util.*;
import java.io.*;
import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.json.JsonMapper;
import io.github.gustavo2358.lower.source.QualifiedSourceDependencies;
import io.github.gustavo2358.lower.source.QualifiedSourceDependencies.*;
/** Closed v1 codec with explicit field mapping; no polymorphic/bean deserialization. */
public final class QualifiedSourceJson {
    private final ObjectMapper mapper=JsonMapper.builder(JsonFactory.builder().enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).build()).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS).build();
    public QualifiedSourceDependencies decode(byte[] bytes) throws IOException {
        var n=mapper.readTree(bytes);
        if(n==null || !n.path("schema").asText().equals("qualified-source-dependencies") || !n.path("version").asText().equals("1.0.0"))throw new IllegalArgumentException("unsupported source contract");
        return readQualifiedSourceDependencies(n);
    }
    public byte[] encode(QualifiedSourceDependencies value) throws IOException {return mapper.writeValueAsBytes(value(value));}
    public static Map<String,Object> value(QualifiedSourceDependencies v) {return object("schema", v.schema(), "version", v.version(), "producer", v.producer(), "source", value(v.source()), "air", v.air().stream().map(QualifiedSourceJson::value).toList(), "units", v.units().stream().map(QualifiedSourceJson::value).toList());}
    private static QualifiedSourceDependencies readQualifiedSourceDependencies(JsonNode n) {keys(n, "schema", "version", "producer", "source", "air", "units");return new QualifiedSourceDependencies(text(n.get("schema")), text(n.get("version")), text(n.get("producer")), readDocument(n.get("source")), list(n.get("air"), QualifiedSourceJson::readAirCorrelation), list(n.get("units"), QualifiedSourceJson::readUnitEvidence));}
    public static Map<String,Object> value(Document v) {return object("schema", v.schema(), "version", v.version(), "sha256", v.sha256());}
    private static Document readDocument(JsonNode n) {keys(n, "schema", "version", "sha256");return new Document(text(n.get("schema")), text(n.get("version")), text(n.get("sha256")));}
    public static Map<String,Object> value(AirCorrelation v) {return object("publication", v.publication(), "sha256", v.sha256());}
    private static AirCorrelation readAirCorrelation(JsonNode n) {keys(n, "publication", "sha256");return new AirCorrelation(text(n.get("publication")), text(n.get("sha256")));}
    public static Map<String,Object> value(UnitId v) {return object("compilationUnitId", v.compilationUnitId(), "structuralPath", v.structuralPath(), "canonicalProgramName", v.canonicalProgramName());}
    private static UnitId readUnitId(JsonNode n) {keys(n, "compilationUnitId", "structuralPath", "canonicalProgramName");return new UnitId(text(n.get("compilationUnitId")), list(n.get("structuralPath"), QualifiedSourceJson::integer), text(n.get("canonicalProgramName")));}
    public static Map<String,Object> value(StatementId v) {return object("unit", value(v.unit()), "handle", v.handle());}
    private static StatementId readStatementId(JsonNode n) {keys(n, "unit", "handle");return new StatementId(readUnitId(n.get("unit")), text(n.get("handle")));}
    public static Map<String,Object> value(OperandId v) {return object("statement", value(v.statement()), "handle", v.handle());}
    private static OperandId readOperandId(JsonNode n) {keys(n, "statement", "handle");return new OperandId(readStatementId(n.get("statement")), text(n.get("handle")));}
    public static Map<String,Object> value(Location v) {return object("file", v.file(), "startLine", v.startLine(), "startColumn", v.startColumn(), "endLine", v.endLine(), "endColumn", v.endColumn());}
    private static Location readLocation(JsonNode n) {keys(n, "file", "startLine", "startColumn", "endLine", "endColumn");return new Location(text(n.get("file")), integer(n.get("startLine")), integer(n.get("startColumn")), integer(n.get("endLine")), integer(n.get("endColumn")));}
    public static Map<String,Object> value(Include v) {return object("includingFile", v.includingFile(), "requestedName", v.requestedName(), "includedFile", v.includedFile(), "includeLine", v.includeLine());}
    private static Include readInclude(JsonNode n) {keys(n, "includingFile", "requestedName", "includedFile", "includeLine");return new Include(text(n.get("includingFile")), text(n.get("requestedName")), text(n.get("includedFile")), integer(n.get("includeLine")));}
    public static Map<String,Object> value(Provenance v) {return object("expanded", value(v.expanded()), "original", value(v.original()), "includeChain", v.includeChain().stream().map(QualifiedSourceJson::value).toList(), "exact", v.exact());}
    private static Provenance readProvenance(JsonNode n) {keys(n, "expanded", "original", "includeChain", "exact");return new Provenance(readLocation(n.get("expanded")), readLocation(n.get("original")), list(n.get("includeChain"), QualifiedSourceJson::readInclude), bool(n.get("exact")));}
    public static Map<String,Object> value(Statement v) {return object("id", value(v.id()), "provenance", value(v.provenance()));}
    private static Statement readStatement(JsonNode n) {keys(n, "id", "provenance");return new Statement(readStatementId(n.get("id")), readProvenance(n.get("provenance")));}
    public static Map<String,Object> value(Operand v) {return object("id", value(v.id()), "provenance", value(v.provenance()));}
    private static Operand readOperand(JsonNode n) {keys(n, "id", "provenance");return new Operand(readOperandId(n.get("id")), readProvenance(n.get("provenance")));}
    public static Map<String,Object> value(Value v) {return object("logicalDomain", v.logicalDomain(), "value", v.value(), "logicalExtent", v.logicalExtent());}
    private static Value readValue(JsonNode n) {keys(n, "logicalDomain", "value", "logicalExtent");return new Value(text(n.get("logicalDomain")), text(n.get("value")), integer(n.get("logicalExtent")));}
    public static Map<String,Object> value(Occurrence v) {return object("id", value(v.id()), "technology", v.technology(), "command", v.command(), "namespace", v.namespace(), "nameProfile", v.nameProfile(), "targetKind", v.targetKind(), "operands", v.operands().stream().map(QualifiedSourceJson::value).toList(), "values", v.values().stream().map(QualifiedSourceJson::value).toList(), "valueRemainder", v.valueRemainder(), "qualifications", v.qualifications());}
    private static Occurrence readOccurrence(JsonNode n) {keys(n, "id", "technology", "command", "namespace", "nameProfile", "targetKind", "operands", "values", "valueRemainder", "qualifications");return new Occurrence(readStatementId(n.get("id")), text(n.get("technology")), text(n.get("command")), text(n.get("namespace")), text(n.get("nameProfile")), text(n.get("targetKind")), list(n.get("operands"), QualifiedSourceJson::readOperand), list(n.get("values"), QualifiedSourceJson::readValue), bool(n.get("valueRemainder")), list(n.get("qualifications"), QualifiedSourceJson::text));}
    public static Map<String,Object> value(Support v) {return object("kind", v.kind(), "target", v.target(), "activation", v.activation().stream().map(QualifiedSourceJson::value).toList(), "cause", v.cause());}
    private static Support readSupport(JsonNode n) {keys(n, "kind", "target", "activation", "cause");return new Support(text(n.get("kind")), list(n.get("target"), QualifiedSourceJson::text), list(n.get("activation"), QualifiedSourceJson::readStatementId), text(n.get("cause")));}
    public static Map<String,Object> value(Node v) {return object("id", v.id(), "context", v.context(), "location", v.location(), "support", value(v.support()));}
    private static Node readNode(JsonNode n) {keys(n, "id", "context", "location", "support");return new Node(text(n.get("id")), text(n.get("context")), text(n.get("location")), readSupport(n.get("support")));}
    public static Map<String,Object> value(Registration v) {return object("statement", value(v.statement()), "statementOrigin", value(v.statementOrigin()), "operandOrigin", value(v.operandOrigin()));}
    private static Registration readRegistration(JsonNode n) {keys(n, "statement", "statementOrigin", "operandOrigin");return new Registration(readStatementId(n.get("statement")), readProvenance(n.get("statementOrigin")), readProvenance(n.get("operandOrigin")));}
    public static Map<String,Object> value(Target v) {return object("id", v.id(), "form", v.form(), "entry", v.entry().stream().map(QualifiedSourceJson::value).toList(), "registrations", v.registrations().stream().map(QualifiedSourceJson::value).toList(), "programOperands", v.programOperands().stream().map(QualifiedSourceJson::value).toList(), "programValues", v.programValues().stream().map(QualifiedSourceJson::value).toList());}
    private static Target readTarget(JsonNode n) {keys(n, "id", "form", "entry", "registrations", "programOperands", "programValues");return new Target(text(n.get("id")), text(n.get("form")), list(n.get("entry"), QualifiedSourceJson::readStatementId), list(n.get("registrations"), QualifiedSourceJson::readRegistration), list(n.get("programOperands"), QualifiedSourceJson::readOperand), list(n.get("programValues"), QualifiedSourceJson::readValue));}
    public static Map<String,Object> value(Proof v) {return object("id", v.id(), "kind", v.kind(), "rule", v.rule(), "provenance", value(v.provenance()), "dependencies", v.dependencies());}
    private static Proof readProof(JsonNode n) {keys(n, "id", "kind", "rule", "provenance", "dependencies");return new Proof(text(n.get("id")), text(n.get("kind")), text(n.get("rule")), readProvenance(n.get("provenance")), list(n.get("dependencies"), QualifiedSourceJson::text));}
    public static Map<String,Object> value(Guard v) {return object("id", v.id(), "event", v.event(), "kind", v.kind());}
    private static Guard readGuard(JsonNode n) {keys(n, "id", "event", "kind");return new Guard(text(n.get("id")), text(n.get("event")), text(n.get("kind")));}
    public static Map<String,Object> value(Event v) {return object("id", v.id(), "statement", value(v.statement()), "origin", v.origin(), "disposition", v.disposition(), "eligibility", v.eligibility(), "scope", v.scope(), "runtimeIdentity", v.runtimeIdentity(), "guards", v.guards(), "proofs", v.proofs());}
    private static Event readEvent(JsonNode n) {keys(n, "id", "statement", "origin", "disposition", "eligibility", "scope", "runtimeIdentity", "guards", "proofs");return new Event(text(n.get("id")), readStatementId(n.get("statement")), text(n.get("origin")), text(n.get("disposition")), text(n.get("eligibility")), text(n.get("scope")), text(n.get("runtimeIdentity")), list(n.get("guards"), QualifiedSourceJson::text), list(n.get("proofs"), QualifiedSourceJson::text));}
    public static Map<String,Object> value(Selection v) {return object("id", v.id(), "event", v.event(), "source", v.source(), "target", v.target(), "stateOnEntry", v.stateOnEntry().stream().map(QualifiedSourceJson::value).toList(), "localEntry", v.localEntry(), "guards", v.guards(), "proofs", v.proofs(), "unknownLocalRemainder", v.unknownLocalRemainder(), "localInactivePossible", v.localInactivePossible(), "outerLevelRemainder", v.outerLevelRemainder(), "bypassed", v.bypassed());}
    private static Selection readSelection(JsonNode n) {keys(n, "id", "event", "source", "target", "stateOnEntry", "localEntry", "guards", "proofs", "unknownLocalRemainder", "localInactivePossible", "outerLevelRemainder", "bypassed");return new Selection(text(n.get("id")), text(n.get("event")), text(n.get("source")), list(n.get("target"), QualifiedSourceJson::text), list(n.get("stateOnEntry"), QualifiedSourceJson::readSupport), list(n.get("localEntry"), QualifiedSourceJson::text), list(n.get("guards"), QualifiedSourceJson::text), list(n.get("proofs"), QualifiedSourceJson::text), bool(n.get("unknownLocalRemainder")), bool(n.get("localInactivePossible")), bool(n.get("outerLevelRemainder")), bool(n.get("bypassed")));}
    public static Map<String,Object> value(Derivation v) {return object("id", v.id(), "source", v.source(), "destination", v.destination(), "callerPremise", v.callerPremise(), "authority", v.authority(), "proofs", v.proofs(), "selection", v.selection());}
    private static Derivation readDerivation(JsonNode n) {keys(n, "id", "source", "destination", "callerPremise", "authority", "proofs", "selection");return new Derivation(text(n.get("id")), list(n.get("source"), QualifiedSourceJson::text), text(n.get("destination")), list(n.get("callerPremise"), QualifiedSourceJson::text), text(n.get("authority")), list(n.get("proofs"), QualifiedSourceJson::text), list(n.get("selection"), QualifiedSourceJson::text));}
    public static Map<String,Object> value(Frontier v) {return object("source", v.source(), "authority", v.authority(), "reference", v.reference(), "proofs", v.proofs());}
    private static Frontier readFrontier(JsonNode n) {keys(n, "source", "authority", "reference", "proofs");return new Frontier(text(n.get("source")), text(n.get("authority")), text(n.get("reference")), list(n.get("proofs"), QualifiedSourceJson::text));}
    public static Map<String,Object> value(UnitEvidence v) {return object("unit", value(v.unit()), "controlAvailable", v.controlAvailable(), "statements", v.statements().stream().map(QualifiedSourceJson::value).toList(), "occurrences", v.occurrences().stream().map(QualifiedSourceJson::value).toList(), "targets", v.targets().stream().map(QualifiedSourceJson::value).toList(), "nodes", v.nodes().stream().map(QualifiedSourceJson::value).toList(), "derivations", v.derivations().stream().map(QualifiedSourceJson::value).toList(), "selections", v.selections().stream().map(QualifiedSourceJson::value).toList(), "events", v.events().stream().map(QualifiedSourceJson::value).toList(), "guards", v.guards().stream().map(QualifiedSourceJson::value).toList(), "proofs", v.proofs().stream().map(QualifiedSourceJson::value).toList(), "frontiers", v.frontiers().stream().map(QualifiedSourceJson::value).toList());}
    private static UnitEvidence readUnitEvidence(JsonNode n) {keys(n, "unit", "controlAvailable", "statements", "occurrences", "targets", "nodes", "derivations", "selections", "events", "guards", "proofs", "frontiers");return new UnitEvidence(readUnitId(n.get("unit")), bool(n.get("controlAvailable")), list(n.get("statements"), QualifiedSourceJson::readStatement), list(n.get("occurrences"), QualifiedSourceJson::readOccurrence), list(n.get("targets"), QualifiedSourceJson::readTarget), list(n.get("nodes"), QualifiedSourceJson::readNode), list(n.get("derivations"), QualifiedSourceJson::readDerivation), list(n.get("selections"), QualifiedSourceJson::readSelection), list(n.get("events"), QualifiedSourceJson::readEvent), list(n.get("guards"), QualifiedSourceJson::readGuard), list(n.get("proofs"), QualifiedSourceJson::readProof), list(n.get("frontiers"), QualifiedSourceJson::readFrontier));}
    private static Map<String,Object> object(Object... fields){var m=new TreeMap<String,Object>();for(int i=0;i<fields.length;i+=2)m.put((String)fields[i],fields[i+1]);return m;}
    private static String text(JsonNode n){if(n==null||!n.isTextual())throw new IllegalArgumentException("text required");return n.textValue();}
    private static int integer(JsonNode n){if(n==null||!n.isIntegralNumber()||!n.canConvertToInt())throw new IllegalArgumentException("integer required");return n.intValue();}
    private static boolean bool(JsonNode n){if(n==null||!n.isBoolean())throw new IllegalArgumentException("boolean required");return n.booleanValue();}
    private static <T> List<T> list(JsonNode n,java.util.function.Function<JsonNode,T> f){if(n==null||!n.isArray())throw new IllegalArgumentException("array required");var result=new ArrayList<T>();for(var x:n)result.add(f.apply(x));return List.copyOf(result);}
    private static void keys(JsonNode n,String... keys){if(n==null||!n.isObject())throw new IllegalArgumentException("object required");var actual=new HashSet<String>();n.fieldNames().forEachRemaining(actual::add);if(!actual.equals(Set.of(keys)))throw new IllegalArgumentException("closed source evidence fields");}
}
